import os
from datetime import datetime, timedelta
from airflow import DAG
from airflow.providers.google.cloud.operators.dataproc import (
    DataprocCreateClusterOperator,
    DataprocSubmitJobOperator,
    DataprocDeleteClusterOperator,
)
from airflow.providers.google.cloud.transfers.gcs_to_bigquery import GCSToBigQueryOperator
from airflow.providers.google.cloud.transfers.local_to_gcs import LocalFilesystemToGCSOperator
from airflow.utils.trigger_rule import TriggerRule

# ==========================================
# CONFIGURATION
# ==========================================
PROJECT_ID = os.getenv("GCP_PROJECT_ID", "car-sales-elt")
REGION = "us-central1"
BUCKET = os.getenv("GCP_GCS_BUCKET", "car-sales-landing-zone-ankit")

CLUSTER_NAME = "airflow-dataproc-cluster-{{ ds_nodash }}"
PYSPARK_URI = f"gs://{BUCKET}/scripts/dataproc_transformation.py"

# Inputs/Outputs for PySpark
RAW_DATA_PATH = f"gs://{BUCKET}/raw_data/*/*/*/*.csv"
PROCESSED_DATA_PATH = f"gs://{BUCKET}/processed_data/car_sales_cleaned_tmp_{{{{ ds_nodash }}}}"

# BigQuery Settings
BQ_DATASET = "car_sales_data"
BQ_TABLE = "cleaned_car_sales"

# Cluster Definition (Single Node Cluster to fit in GCP 4-CPU Quota)
CLUSTER_CONFIG = {
    "master_config": {
        "num_instances": 1,
        "machine_type_uri": "e2-standard-4",
        "disk_config": {"boot_disk_type": "pd-standard", "boot_disk_size_gb": 50},
    },
    "gce_cluster_config": {
        "zone_uri": "us-central1-a"
    },
    "software_config": {
        "properties": {
            "dataproc:dataproc.allow.zero.workers": "true"
        }
    }
}

PYSPARK_JOB = {
    "reference": {"project_id": PROJECT_ID},
    "placement": {"cluster_name": CLUSTER_NAME},
    "pyspark_job": {
        "main_python_file_uri": PYSPARK_URI,
        "args": [RAW_DATA_PATH, PROCESSED_DATA_PATH]
    },
}

default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'start_date': datetime(2023, 1, 1),
    'email_on_failure': False,
    'retries': 0,
}

with DAG(
    '2_dataproc_to_bigquery_pipeline',
    default_args=default_args,
    description='Spin up Dataproc, transform, load to BigQuery, and delete cluster',
    schedule_interval=None,
    catchup=False,
    tags=['car_sales', 'transformation', 'dataproc', 'bigquery']
) as dag:

    # 1. Upload PySpark Script dynamically
    upload_script = LocalFilesystemToGCSOperator(
        task_id="upload_pyspark_script",
        src="/opt/airflow/scripts/dataproc_transformation.py",
        dst="scripts/dataproc_transformation.py",
        bucket=BUCKET,
    )

    # 2. Create Dataproc Cluster
    create_cluster = DataprocCreateClusterOperator(
        task_id="create_dataproc_cluster",
        project_id=PROJECT_ID,
        cluster_config=CLUSTER_CONFIG,
        region=REGION,
        cluster_name=CLUSTER_NAME,
    )

    # 2. Submit PySpark Job
    submit_pyspark = DataprocSubmitJobOperator(
        task_id="submit_pyspark_job",
        job=PYSPARK_JOB,
        region=REGION,
        project_id=PROJECT_ID,
    )

    # 3. Load Parquet generated by Spark directly into BigQuery
    # Since BigQuery can natively load Parquet from GCS, we skip JDBC complexities!
    load_to_bq = GCSToBigQueryOperator(
        task_id="load_processed_data_to_bq",
        bucket=BUCKET,
        source_objects=[f"processed_data/car_sales_cleaned_tmp_{{{{ ds_nodash }}}}/*.parquet"],
        destination_project_dataset_table=f"{PROJECT_ID}.{BQ_DATASET}.{BQ_TABLE}",
        source_format="PARQUET",
        write_disposition="WRITE_TRUNCATE", # Complete overwrite for now
        time_partitioning={"type": "MONTH", "field": "sales_yearmonth"}, # BQ Partitioning
        autodetect=True,
    )

    # 4. Delete Cluster automatically even if tasks fail to save money
    delete_cluster = DataprocDeleteClusterOperator(
        task_id="delete_dataproc_cluster",
        project_id=PROJECT_ID,
        cluster_name=CLUSTER_NAME,
        region=REGION,
        trigger_rule=TriggerRule.ALL_DONE, # Run even if upstream failed
    )

    upload_script >> create_cluster >> submit_pyspark >> load_to_bq >> delete_cluster
